### ISSUE TITLE
Derecho environment details

### ISSUE THREAD

**Issue by jsschreck** [NCAR/miles-credit#98]
We gotta get this added to the documentation. I think several of us should go through and verify the env builds correctly.

**Comment by ggantos** [comment]
Attempting to verify install with a single node credit env install following the directions below (from hackathon slack channel):

```
Clone miles-credit or pull from main if already cloned.
Create new environment with
module load conda
conda create -n credit python=3.11
cd miles-credit
pip install .
```

However, when I test submit a batch job via `python applications/rollout_to_netcdf.py -c config/wxformer_1dg_nompi_test.yml`, I receive the following error:

```
Save roll-outs to /glade/derecho/scratch/ggantos/CREDIT/wxformer_1h/
INFO:credit.transforms:Loading stored mean and std data for z-score-based transform and inverse transform
INFO:credit.transforms:Loading stored mean and std data for z-score-based transform and inverse transform
INFO:credit.models:Loading the CrossFormer model with a conv decoder head and skip connections ...
Traceback (most recent call last):
  File "/glade/work/ggantos/miles-credit/applications/rollout_to_netcdf.py", line 565, in <module>
    _ = predict(0, 1, conf, p=p)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/work/ggantos/miles-credit/applications/rollout_to_netcdf.py", line 205, in predict
    model = load_model(conf, load_weights=True).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/work/ggantos/miles-credit/credit/models/__init__.py", line 148, in load_model
    return model.load_model(conf)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/glade/work/ggantos/miles-credit/credit/models/base_model.py", line 68, in load_model
    raise ValueError("No saved checkpoint exists. You must train a model first. Exiting.")
ValueError: No saved checkpoint exists. You must train a model first. Exiting.
```

**Comment by djgagne** [comment]
Derecho environment issues have been addressed with the `create_derecho_env.sh` script.
